import { Account, Category, Transaction, Budget, UserSettings } from '../types';

export const DEFAULT_USER_SETTINGS: UserSettings = {
  currency: 'BDT',
  theme: 'dark',
  dateFormat: 'MMM dd, yyyy',
  firstDayOfWeek: 'sunday',
  defaultTransactionType: 'expense',
  confirmBeforeDelete: true,
  startScreen: 'records',
};

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc-cash',
    name: 'Cash',
    type: 'Cash',
    icon: 'Cash',
    color: '#84cc16',
    initialBalance: 25000,
    currentBalance: 25000,
    currency: 'BDT',
    description: 'Physical cash wallet',
  },
  {
    id: 'acc-bank',
    name: 'Bank',
    type: 'Bank',
    icon: 'Bank',
    color: '#3b82f6',
    initialBalance: 120000,
    currentBalance: 120000,
    currency: 'BDT',
    description: 'Primary savings bank account',
  },
  {
    id: 'acc-bkash',
    name: 'bKash',
    type: 'bKash',
    icon: 'bKash',
    color: '#ec4899',
    initialBalance: 15500,
    currentBalance: 15500,
    currency: 'BDT',
    description: 'bKash personal wallet',
  },
  {
    id: 'acc-nagad',
    name: 'Nagad',
    type: 'Nagad',
    icon: 'Nagad',
    color: '#f97316',
    initialBalance: 5000,
    currentBalance: 5000,
    currency: 'BDT',
    description: 'Nagad personal wallet',
  },
  {
    id: 'acc-cc',
    name: 'Credit Card',
    type: 'Credit Card',
    icon: 'Credit Card',
    color: '#a855f7',
    initialBalance: 0,
    currentBalance: 0,
    currency: 'BDT',
    description: 'Credit Card limit',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  // Expense Categories
  { id: 'cat-exp-food', name: 'Food', type: 'expense', icon: 'Food', color: '#ef4444', isDefault: true, order: 1 },
  { id: 'cat-exp-bills', name: 'Bills', type: 'expense', icon: 'Bills', color: '#64748b', isDefault: true, order: 2 },
  { id: 'cat-exp-health', name: 'Health', type: 'expense', icon: 'Health', color: '#f43f5e', isDefault: true, order: 3 },
  { id: 'cat-exp-shopping', name: 'Shopping', type: 'expense', icon: 'Shopping', color: '#0ea5e9', isDefault: true, order: 4 },
  { id: 'cat-exp-transport', name: 'Transportation', type: 'expense', icon: 'Transportation', color: '#3b82f6', isDefault: true, order: 5 },
  { id: 'cat-exp-home', name: 'Home', type: 'expense', icon: 'Home', color: '#d946ef', isDefault: true, order: 6 },
  { id: 'cat-exp-baby', name: 'Baby', type: 'expense', icon: 'Baby', color: '#e11d48', isDefault: true, order: 7 },
  { id: 'cat-exp-education', name: 'Education', type: 'expense', icon: 'Education', color: '#8b5cf6', isDefault: true, order: 8 },
  { id: 'cat-exp-electronics', name: 'Electronics', type: 'expense', icon: 'Electronics', color: '#14b8a6', isDefault: true, order: 9 },
  { id: 'cat-exp-cosmetics', name: 'Cosmetics', type: 'expense', icon: 'Cosmetics', color: '#ec4899', isDefault: true, order: 10 },
  { id: 'cat-exp-bike', name: 'Bike', type: 'expense', icon: 'Bike', color: '#7c3aed', isDefault: true, order: 11 },
  { id: 'cat-exp-car', name: 'Car', type: 'expense', icon: 'Car', color: '#6366f1', isDefault: true, order: 12 },
  { id: 'cat-exp-gas', name: 'Gas/Fuel', type: 'expense', icon: 'Gas/Fuel', color: '#f59e0b', isDefault: true, order: 13 },
  { id: 'cat-exp-social', name: 'Social/Donate', type: 'expense', icon: 'Social/Donate', color: '#10b981', isDefault: true, order: 14 },
  { id: 'cat-exp-gift', name: 'Gift Cost', type: 'expense', icon: 'Gift Cost', color: '#f97316', isDefault: true, order: 15 },
  { id: 'cat-exp-entertainment', name: 'Entertainment', type: 'expense', icon: 'Entertainment', color: '#84cc16', isDefault: true, order: 16 },
  { id: 'cat-exp-travel', name: 'Travel', type: 'expense', icon: 'Travel', color: '#06b6d4', isDefault: true, order: 17 },
  { id: 'cat-exp-others', name: 'Others', type: 'expense', icon: 'Others', color: '#78716c', isDefault: true, order: 18 },

  // Income Categories
  { id: 'cat-inc-salary', name: 'Salary', type: 'income', icon: 'Salary', color: '#22c55e', isDefault: true, order: 1 },
  { id: 'cat-inc-freelance', name: 'Freelance', type: 'income', icon: 'Freelance', color: '#10b981', isDefault: true, order: 2 },
  { id: 'cat-inc-business', name: 'Business', type: 'income', icon: 'Business', color: '#3b82f6', isDefault: true, order: 3 },
  { id: 'cat-inc-sale', name: 'Sale', type: 'income', icon: 'Sale', color: '#84cc16', isDefault: true, order: 4 },
  { id: 'cat-inc-rental', name: 'Rental', type: 'income', icon: 'Rental', color: '#a855f7', isDefault: true, order: 5 },
  { id: 'cat-inc-awards', name: 'Awards', type: 'income', icon: 'Awards', color: '#eab308', isDefault: true, order: 6 },
  { id: 'cat-inc-grants', name: 'Grants', type: 'income', icon: 'Grants', color: '#06b6d4', isDefault: true, order: 7 },
  { id: 'cat-inc-refunds', name: 'Refunds', type: 'income', icon: 'Refunds', color: '#14b8a6', isDefault: true, order: 8 },
  { id: 'cat-inc-other', name: 'Other Income', type: 'income', icon: 'Other Income', color: '#64748b', isDefault: true, order: 9 },
];

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-001',
    type: 'expense',
    amount: 5560,
    accountId: 'acc-cash',
    categoryId: 'cat-exp-health',
    note: 'doctor consultation',
    date: '2026-09-13T14:30:00',
  },
  {
    id: 'tx-002',
    type: 'expense',
    amount: 3260,
    accountId: 'acc-cash',
    categoryId: 'cat-exp-shopping',
    note: 'baby shopping',
    date: '2026-09-13T11:15:00',
  },
  {
    id: 'tx-003',
    type: 'expense',
    amount: 5250,
    accountId: 'acc-cash',
    categoryId: 'cat-exp-home',
    note: 'home decor & utilities',
    date: '2026-09-12T17:40:00',
  },
  {
    id: 'tx-004',
    type: 'expense',
    amount: 300,
    accountId: 'acc-cash',
    categoryId: 'cat-exp-bills',
    note: 'electricity bill voucher',
    date: '2026-09-12T15:20:00',
  },
  {
    id: 'tx-005',
    type: 'expense',
    amount: 4855,
    accountId: 'acc-cash',
    categoryId: 'cat-exp-health',
    note: 'prescription medicine pharmacy',
    date: '2026-09-12T10:00:00',
  },
  {
    id: 'tx-006',
    type: 'expense',
    amount: 100,
    accountId: 'acc-cash',
    categoryId: 'cat-exp-food',
    note: 'afternoon tea & snack',
    date: '2026-09-11T16:00:00',
  },
  {
    id: 'tx-007',
    type: 'expense',
    amount: 225,
    accountId: 'acc-cash',
    categoryId: 'cat-exp-health',
    note: 'first aid kit essentials',
    date: '2026-09-11T12:30:00',
  },
  {
    id: 'tx-008',
    type: 'expense',
    amount: 500,
    accountId: 'acc-cash',
    categoryId: 'cat-exp-social',
    note: 'charity donation',
    date: '2026-09-11T09:15:00',
  },
  {
    id: 'tx-009',
    type: 'expense',
    amount: 1650,
    accountId: 'acc-cash',
    categoryId: 'cat-exp-transport',
    note: 'weekly commute & taxi',
    date: '2026-09-10T18:45:00',
  },
  {
    id: 'tx-010',
    type: 'expense',
    amount: 1350,
    accountId: 'acc-cash',
    categoryId: 'cat-exp-baby',
    note: 'baby diapers & cereal',
    date: '2026-09-09T14:10:00',
  },
  {
    id: 'tx-011',
    type: 'expense',
    amount: 1790,
    accountId: 'acc-cash',
    categoryId: 'cat-exp-food',
    note: 'family restaurant dinner',
    date: '2026-09-08T20:00:00',
  },
  {
    id: 'tx-012',
    type: 'income',
    amount: 50000,
    accountId: 'acc-bank',
    categoryId: 'cat-inc-salary',
    note: 'Monthly salary credit',
    date: '2026-09-01T09:00:00',
  },
  // August 2026
  { id: 'tx-0801', type: 'expense', amount: 8500, accountId: 'acc-cash', categoryId: 'cat-exp-food', note: 'Monthly groceries & food', date: '2026-08-15T12:00:00' },
  { id: 'tx-0802', type: 'expense', amount: 6400, accountId: 'acc-cash', categoryId: 'cat-exp-shopping', note: 'Clothing and shoes', date: '2026-08-18T16:30:00' },
  { id: 'tx-0803', type: 'expense', amount: 3200, accountId: 'acc-bank', categoryId: 'cat-exp-bills', note: 'Internet and utility bill', date: '2026-08-05T10:00:00' },
  { id: 'tx-0804', type: 'expense', amount: 2200, accountId: 'acc-bkash', categoryId: 'cat-exp-transport', note: 'Ride sharing & commute', date: '2026-08-22T09:15:00' },
  { id: 'tx-0805', type: 'expense', amount: 1800, accountId: 'acc-cash', categoryId: 'cat-exp-entertainment', note: 'Cinema & weekend outings', date: '2026-08-28T20:00:00' },
  { id: 'tx-0806', type: 'income', amount: 50000, accountId: 'acc-bank', categoryId: 'cat-inc-salary', note: 'August salary', date: '2026-08-01T09:00:00' },
  // July 2026
  { id: 'tx-0701', type: 'expense', amount: 7800, accountId: 'acc-cash', categoryId: 'cat-exp-food', note: 'Supermarket shopping', date: '2026-07-12T14:00:00' },
  { id: 'tx-0702', type: 'expense', amount: 12000, accountId: 'acc-cc', categoryId: 'cat-exp-shopping', note: 'Festival shopping', date: '2026-07-19T18:00:00' },
  { id: 'tx-0703', type: 'expense', amount: 4500, accountId: 'acc-cash', categoryId: 'cat-exp-home', note: 'Home repairs & kitchenware', date: '2026-07-08T11:00:00' },
  { id: 'tx-0704', type: 'expense', amount: 3100, accountId: 'acc-bank', categoryId: 'cat-exp-bills', note: 'Gas and electric bill', date: '2026-07-04T10:00:00' },
  { id: 'tx-0705', type: 'expense', amount: 2500, accountId: 'acc-bkash', categoryId: 'cat-exp-transport', note: 'Transport fares', date: '2026-07-25T08:30:00' },
  { id: 'tx-0706', type: 'income', amount: 50000, accountId: 'acc-bank', categoryId: 'cat-inc-salary', note: 'July salary', date: '2026-07-01T09:00:00' },
  // June 2026
  { id: 'tx-0601', type: 'expense', amount: 7200, accountId: 'acc-cash', categoryId: 'cat-exp-food', note: 'Dining out & groceries', date: '2026-06-14T13:00:00' },
  { id: 'tx-0602', type: 'expense', amount: 14000, accountId: 'acc-bank', categoryId: 'cat-exp-travel', note: 'Summer vacation resort', date: '2026-06-20T17:00:00' },
  { id: 'tx-0603', type: 'expense', amount: 5000, accountId: 'acc-cash', categoryId: 'cat-exp-shopping', note: 'Gifts & summer gear', date: '2026-06-22T15:30:00' },
  { id: 'tx-0604', type: 'expense', amount: 3000, accountId: 'acc-bank', categoryId: 'cat-exp-bills', note: 'Quarterly utilities', date: '2026-06-05T10:00:00' },
  { id: 'tx-0605', type: 'expense', amount: 1800, accountId: 'acc-cash', categoryId: 'cat-exp-transport', note: 'Monthly metro pass', date: '2026-06-02T08:00:00' },
  { id: 'tx-0606', type: 'income', amount: 50000, accountId: 'acc-bank', categoryId: 'cat-inc-salary', note: 'June salary', date: '2026-06-01T09:00:00' },
  // May 2026
  { id: 'tx-0501', type: 'expense', amount: 8100, accountId: 'acc-cash', categoryId: 'cat-exp-food', note: 'Groceries & fruits', date: '2026-05-10T12:00:00' },
  { id: 'tx-0502', type: 'expense', amount: 18500, accountId: 'acc-cc', categoryId: 'cat-exp-electronics', note: 'Tablet & accessories', date: '2026-05-18T16:00:00' },
  { id: 'tx-0503', type: 'expense', amount: 3400, accountId: 'acc-cash', categoryId: 'cat-exp-health', note: 'Dental clinic visit', date: '2026-05-24T11:00:00' },
  { id: 'tx-0504', type: 'expense', amount: 2900, accountId: 'acc-bank', categoryId: 'cat-exp-bills', note: 'Electricity bill', date: '2026-05-06T09:00:00' },
  { id: 'tx-0505', type: 'expense', amount: 2000, accountId: 'acc-bkash', categoryId: 'cat-exp-transport', note: 'Taxi & ride commute', date: '2026-05-27T08:30:00' },
  { id: 'tx-0506', type: 'income', amount: 50000, accountId: 'acc-bank', categoryId: 'cat-inc-salary', note: 'May salary', date: '2026-05-01T09:00:00' },
  // April 2026
  { id: 'tx-0401', type: 'expense', amount: 7600, accountId: 'acc-cash', categoryId: 'cat-exp-food', note: 'Family dining & provisions', date: '2026-04-11T13:00:00' },
  { id: 'tx-0402', type: 'expense', amount: 4200, accountId: 'acc-cash', categoryId: 'cat-exp-shopping', note: 'Casual clothing', date: '2026-04-16T15:00:00' },
  { id: 'tx-0403', type: 'expense', amount: 3000, accountId: 'acc-cash', categoryId: 'cat-exp-social', note: 'Charity & aid donation', date: '2026-04-20T10:00:00' },
  { id: 'tx-0404', type: 'expense', amount: 2800, accountId: 'acc-bank', categoryId: 'cat-exp-bills', note: 'Internet broadband bill', date: '2026-04-05T09:30:00' },
  { id: 'tx-0405', type: 'expense', amount: 1900, accountId: 'acc-bkash', categoryId: 'cat-exp-transport', note: 'City travel commute', date: '2026-04-25T08:00:00' },
  { id: 'tx-0406', type: 'income', amount: 50000, accountId: 'acc-bank', categoryId: 'cat-inc-salary', note: 'April salary', date: '2026-04-01T09:00:00' },
];

export const DEMO_BUDGETS: Budget[] = [
  { id: 'bgt-1', month: '2026-09', categoryId: 'cat-exp-food', amount: 8000 },
  { id: 'bgt-2', month: '2026-09', categoryId: 'cat-exp-shopping', amount: 10000 },
  { id: 'bgt-3', month: '2026-09', categoryId: 'cat-exp-health', amount: 5000 },
  { id: 'bgt-4', month: '2026-09', categoryId: 'cat-exp-home', amount: 6000 },
  { id: 'bgt-5', month: '2026-09', categoryId: 'cat-exp-transport', amount: 3000 },
];
